version: 2.1

orbs:
  maven: circleci/maven@1.0.0
  aws-ecr: circleci/aws-ecr@6.7.1
  aws-ecs: circleci/aws-ecs@1.1.0

jobs:
  test-dev:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Test dev"

  merge-dev-into-staging:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Merge dev into staging"

  test-staging:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Test staging"

  release-staging:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Release staging"

  send_start_notification:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Sending a notification to the users"

  send_end_notification:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Prod ok, let's have a beer"

workflows:
  build-test-feature:
    jobs:
      - maven/test:
          filters:
            branches:
              only:
                - /feature-.*/

  build-test-deploy-dev:
    jobs:
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only:
                - dev
          create-repo: true
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: 'latest,${CIRCLE_SHA1}'

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"

      - test-dev:
          requires:
            - aws-ecs/deploy-service-update

      - merge-dev-into-staging:
          requires:
            - test-dev

  release-deploy-staging:
    jobs:
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only:
                - staging
          create-repo: true
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: 'staging,${CIRCLE_SHA1}'

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"

      - test-staging:
          requires:
            - aws-ecs/deploy-service-update

      - release-staging:
          requires:
            - test-staging

  build-test-deploy-prod:
    jobs:
      - send_start_notification

      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only:
                - master
          create-repo: true
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: '1.0.0-RELEASE,${CIRCLE_SHA1}'

      - approval-prod:
          requires:
            - aws-ecr/build-and-push-image
          type: approval

      - aws-ecs/deploy-service-update:
          requires:
            - approval-prod
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"

      - send_end_notification:
          requires:
            - aws-ecs/deploy-service-update