version: 2.1

orbs:
  gradle: circleci/gradle@2.1.0

executors:
  executor-java:
    docker:
      - image: circleci/openjdk:13-jdk-buster
        environment:
          PROJECT: mathieuaime
          MAVEN_OPTS: -Xmx3200m

jobs:
  build_and_publish:
    executor: executor-java
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - setup_remote_docker
      - run:
          name: Packaging
          command: ./gradlew build
      - save_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: Build Docker Image
          command: docker build -t $PROJECT/$CIRCLE_PROJECT_REPONAME .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $PROJECT/$CIRCLE_PROJECT_REPONAME
            VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
            docker tag $PROJECT/$CIRCLE_PROJECT_REPONAME $PROJECT/$CIRCLE_PROJECT_REPONAME:${VERSION}
            docker push $PROJECT/$CIRCLE_PROJECT_REPONAME:${VERSION}

workflows:
  gradle_test:
    jobs:
      - gradle/test
      - build_and_publish:
          requires:
            - gradle/test
          filters:
            branches:
              only:
                - master