version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.1

workflows:
  main:
    jobs:
      - aws-ecr/build-and-push-image:
          create-repo: true
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: AWS_DEFAULT_REGION
          tag: 'latest,${CIRCLE_SHA1}'